import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import {
  Anchor,
  ArrowDownUp,
  ArrowUp,
  Check,
  Clipboard,
  Command,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  Contrast,
  Copy,
  CornerLeftUp,
  Download,
  File,
  FileBraces,
  FileCode,
  FileCog,
  FileDiff,
  FileTerminal,
  FileText,
  Funnel,
  Scissors,
  Folder,
  Image,
  GripVertical,
  Info,
  KeyRound,
  LUCIDE_ICONS,
  LayoutGrid,
  Lock,
  LogOut,
  FolderPlus,
  LucideAngularModule,
  LucideIconProvider,
  Monitor,
  Moon,
  Palette,
  Pencil,
  RefreshCw,
  Rows3,
  ScrollText,
  Search,
  Sparkles,
  SquareTerminal,
  Server,
  Settings,
  ShieldCheck,
  SquarePen,
  Sun,
  Trash2,
  Upload,
  X,
} from 'lucide-angular';

// Registre des icônes Lucide utilisées par l'application.
const ICONS = {
  anchor: Anchor,
  folder: Folder,
  file: File,
  // Icônes par type de fichier (voir `services/file-icon.ts`).
  'file-code': FileCode,
  'file-json': FileBraces,
  'file-text': FileText,
  'file-shell': FileTerminal,
  'file-config': FileCog,
  'file-diff': FileDiff,
  'file-image': Image,
  'arrow-up': ArrowUp,
  'arrow-down-up': ArrowDownUp,
  'corner-up': CornerLeftUp,
  grip: GripVertical,
  check: Check,
  'chevron-down': ChevronDown,
  clipboard: Clipboard,
  command: Command,
  funnel: Funnel,
  scissors: Scissors,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'log-out': LogOut,
  sun: Sun,
  moon: Moon,
  contrast: Contrast,
  copy: Copy,
  'alert-circle': CircleAlert,
  info: Info,
  key: KeyRound,
  monitor: Monitor,
  server: Server,
  logs: ScrollText,
  search: Search,
  terminal: SquareTerminal,
  download: Download,
  upload: Upload,
  settings: Settings,
  close: X,
  trash: Trash2,
  pencil: Pencil,
  'folder-plus': FolderPlus,
  refresh: RefreshCw,
  sparkles: Sparkles,
  palette: Palette,
  edit: SquarePen,
  'layout-grid': LayoutGrid,
  lock: Lock,
  'shield-check': ShieldCheck,
  rows: Rows3,
} as const;

export type IconName = keyof typeof ICONS;

@Component({
  selector: 'app-icon',
  imports: [LucideAngularModule],
  providers: [{ provide: LUCIDE_ICONS, multi: true, useValue: new LucideIconProvider(ICONS) }],
  template: `<lucide-icon [img]="icon()" [size]="size()" [strokeWidth]="2" />`,
  styles: `
    :host {
      display: inline-flex;
      line-height: 0;
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Icon {
  readonly name = input.required<IconName>();
  readonly size = input(20);

  protected readonly icon = computed(() => ICONS[this.name()]);
}
